module.exports = {
    purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        // maxWidth: {
        // 	'10vw': '10vw',
        // 	'20vw': '20vw',
        // 	'30vw': '30vw',
        // 	'40vw': '40vw',
        // 	'50vw': '50vw',
        // 	'60vw': '60vw',
        // 	'70vw': '70vw',
        // 	'80vw': '80vw',
        // 	'90vw': '90vw',
        // },
        maxHeight: {
            "10vh": "10vh",
            "20vh": "20vh",
            "30vh": "30vh",
            "40vh": "40vh",
            "50vh": "50vh",
            "60vh": "60vh",
            "70vh": "70vh",
            "80vh": "80vh",
            "90vh": "90vh",
        },
        extend: {
            colors: {
                lightbeige: "#FEF9EF",
                beige: "#F9E0AE",
                orange: "#FC8621",
                lightorange: "#FD9740",
                darkorange: "#CD6207",
                lightbrown: "#C24914",
                darkbrown: "#682C0E",
            },
            outline: {
                orange: "1px solid #FC8621",
            },
            fontFamily: {
                body: ["Public Sans"],
                title: ["Playfair Display"],
                404: ["Graduate"],
            },
            width: {
                "10vw": "10vw",
                "20vw": "20vw",
                "30vw": "30vw",
                "40vw": "40vw",
                "50vw": "50vw",
                "60vw": "60vw",
                "70vw": "70vw",
                "80vw": "80vw",
                "90vw": "90vw",
                "31p": "31%",
                "23p": "23%",
            },
            height: {
                "10vh": "10vh",
                "20vh": "20vh",
                "30vh": "30vh",
                "40vh": "40vh",
                "50vh": "50vh",
                "60vh": "60vh",
                "70vh": "70vh",
                "80vh": "80vh",
                "90vh": "90vh",
            },
            inset: {
                "10p": "10%",
                "20p": "20%",
                "30p": "30%",
                "40p": "40%",
                "50p": "50%",
                "60p": "60%",
                "70p": "70%",
                "80p": "80%",
                "90p": "90%",
                n10p: "-10%",
                n20p: "-20%",
                n30p: "-30%",
                n40p: "-40%",
                n50p: "-50%",
                n60p: "-60%",
                n70p: "-70%",
                n80p: "-80%",
                n90p: "-90%",
            },
        },
    },
    variants: {
        extend: {
            borderWidth: ["hover", "focus"],
            translate: ["active"],
            backgroundColor: ["active", "disabled", "hover"],
            scale: ["active"],
            cursor: ["disabled", "hover"],
            textColor: ["active", "hover"],
        },
    },
    plugins: [require("tailwind-caret-color")()],
};
